"""
Django settings for tavarat_kiertoon project.

Generated by 'django-admin startproject' using Django 4.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import json
from datetime import timedelta
from pathlib import Path
import os
from decouple import Csv, config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", cast=bool)
TEST_DEBUG = config("TEST_DEBUG", cast=bool)
SECURE_SSL_REDIRECT = config("REDIRECT_SSL", cast=bool)
ALLOWED_HOSTS = config("ALLOWED_HOSTS", cast=Csv())

CORS_ORIGIN_ALLOW_ALL = False
CORS_ALLOWED_ORIGINS = config("CORS_ALLOWED_ORIGINS", cast=Csv())
CSRF_TRUSTED_ORIGINS = config("CORS_ALLOWED_ORIGINS", cast=Csv())

CORS_ALLOW_CREDENTIALS = True

# Application definition

INSTALLED_APPS = [
    # Database apps
    "bulletins",
    "contact_forms",
    "categories",
    "mptt",
    "products",
    "users",
    "rest_framework",
    "rest_framework_simplejwt",
    "orders",
    "bikes",
    "corsheaders",
    "django_filters",
    # Django apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "drf_spectacular",
    "holidays",
    "django_crontab",
    "pauseshop",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "tavarat_kiertoon.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "tavarat_kiertoon.wsgi.application"

REST_FRAMEWORK = {
    "DEFAULT_FILTER_BACKENDS": ("django_filters.rest_framework.DjangoFilterBackend",),
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        # "users.authenticate.CustomJWTAuthentication",  # <--- this ok????
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "EXCEPTION_HANDLER": "tavarat_kiertoon.exceptions.custom_exception_handler",
}
# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }
DATABASES = {
    "default": {
        "ENGINE": config("DATABASE_ENGINE"),
        "NAME": config("DATABASE_NAME"),
        "USER": config("DATABASE_USER"),
        "PASSWORD": config("DATABASE_PASSWORD"),
        "HOST": config("DATABASE_HOST"),
        "PORT": config("DATABASE_PORT"),
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

SIMPLE_JWT = {
    # "ACCESS_TOKEN_LIFETIME": timedelta(minutes=5),
    # "REFRESH_TOKEN_LIFETIME": timedelta(hours=12),
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=int(config("ACCESS_TOKEN_LIFETIME"))),
    "REFRESH_TOKEN_LIFETIME": timedelta(hours=int(config("REFRESH_TOKEN_LIFETIME"))),
    "REFRESH_TOKEN_LIFETIME_REMEMBER_ME": timedelta(
        days=int(config("REFRESH_TOKEN_REMEMBER_ME"))
    ),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": False,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": config("JWT_SECRET_KEY"),
    "VERIFYING_KEY": None,
    "AUDIENCE": None,
    "ISSUER": None,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "JTI_CLAIM": "jti",
    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=5),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=1),
    # custom
    "AUTH_COOKIE": "access_token",  # Cookie name. Enables cookies if value is set.
    "AUTH_COOKIE_REFRESH": "refresh_token",
    "AUTH_COOKIE_DOMAIN": None,  # A string like "example.com", or None for standard domain cookie.
    "AUTH_COOKIE_SECURE": False,  # Whether the auth cookies should be secure (https:// only).
    "AUTH_COOKIE_HTTP_ONLY": True,  # Http only cookie flag.It's not fetch by javascript.
    "AUTH_COOKIE_PATH": "/",  # The path of the auth cookie.
    "AUTH_COOKIE_SAMESITE": "Lax",  # Whether to set the flag restricting cookie leaks on cross-site requests. This can be 'Lax', 'Strict', or None to disable the flag.
}

SPECTACULAR_SETTINGS = {
    "ENUM_NAME_OVERRIDES": {
        "ContactFormStatusEnum": "contact_forms.models.ContactForm.StatusChoices",
        "BikeStateEnum": "bikes.models.BikeStock.StateChoices",
        "OrderStatusEnum": "orders.models.Order.StatusChoices",
        "UserLogEnum": "users.models.UserLogEntry.ActionChoices",
        "BikeRentalEnum": "bikes.models.BikeRental.StateChoices",
    }
}


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Europe/Helsinki"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"

# needs to be checked when ready for deplayment
MEDIA_ROOT = "media/"
MEDIA_URL = "media/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "users.CustomUser"

# setting for allowed domains in email to be used elsewhere in program
VALID_EMAIL_DOMAINS = config("VALID_EMAIL_DOMAINS", cast=Csv())
# if  yo uwant to change the email backendtype do it in the .env file, its default on console

# EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
# EMAIL_BACKEND = "django.core.mail.backends.filebased.EmailBackend"
EMAIL_BACKEND = config("EMAIL_BACKEND")

DEFAULT_EMAIL = config("DEFAULT_EMAIL")

EMAIL_FILE_PATH = BASE_DIR / "sent_emails"

# addresses at front
PASSWORD_RESET_URL_FRONT = config("PASSWORD_RESET_URL_FRONT")
USER_ACTIVATION_URL_FRONT = config("USER_ACTIVATION_URL_FRONT")
EMAIL_CHANGE_URL_FRONT = config("EMAIL_CHANGE_URL_FRONT")

PASSWORD_RESET_TIMEOUT = int(
    config("PASSWORD_RESET_TIMEOUT")
)  # ( 60 * 15 = 900 (sekuntia)(15min))
USER_CREATION_TIMEOUT = int(
    config("USER_CREATION_TIMEOUT")
)  # ( 60 * 60 * 24 * 14 = 1209600 (sekuntia)(2wiikkoa))

# Define the below varibles in .env
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL")
EMAIL_HOST = config("EMAIL_HOST")
EMAIL_HOST_USER = config("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")
EMAIL_PORT = config("EMAIL_PORT")
EMAIL_USE_TLS = config("EMAIL_USE_TLS")

URL_FRONT = config("URL_FRONT")

CRONJOBS = [("0 * * * *", "cron.clear_shopping_carts", ">> /usr/src/app/file.log")]


def add_status_code(record):
    """
    Adds response status code to the log
    :param record:
    :return:
    """
    try:
        record.status_code = record.response.status_code
    except AttributeError:
        record.status_code = ""
    return True


def add_method(record):
    """
    Adds request method to the log
    :param record:
    :return:
    """
    try:
        record.method = record.request.method
    except AttributeError:
        record.method = ""
    return True


def add_response_data(record):
    """
    Adds response data to the log
    :param record:
    :return:
    """
    try:
        record.response_data = record.response.data
    except AttributeError:
        record.response_data = ""
    return True


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": config("LOG_FILE"),
            "maxBytes": 1024 * 1024,  # 1MB
            "backupCount": 5,
            "encoding": "utf-8",
            "formatter": "verbose",
            "filters": ["add_status_code", "add_method", "add_response_data"],
        },
    },
    "formatters": {
        "verbose": {
            "format": "%(asctime)s [%(levelname)s] %(message)s (%(status_code)s %(method)s response: %(response_data)s)",
        },
    },
    "filters": {
        "add_status_code": {
            "()": "django.utils.log.CallbackFilter",
            "callback": add_status_code,
        },
        "add_method": {
            "()": "django.utils.log.CallbackFilter",
            "callback": add_method,
        },
        "add_response_data": {
            "()": "django.utils.log.CallbackFilter",
            "callback": add_response_data,
        },
    },
    "loggers": {
        "": {
            "handlers": ["file"],
            "level": "WARNING",
            "propagate": False,
        },
    },
}
