# Generated by Django 4.1.4 on 2023-03-13 06:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="useraddress",
            old_name="linked_user",
            new_name="user_id",
        ),
    ]
