# Generated by Django 4.1.4 on 2023-02-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_customuser_contact_person_customuser_joint_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useraddress",
            name="user",
        ),
        migrations.AddField(
            model_name="customuser",
            name="address",
            field=models.ManyToManyField(to="users.useraddress"),
        ),
    ]
