# Generated by Django 4.1.4 on 2023-05-17 06:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_customuser_is_active"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="name",
            new_name="first_name",
        ),
        migrations.AddField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
