# Generated by Django 4.1.4 on 2023-03-13 08:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_rename_linked_user_useraddress_user_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="user_name",
            new_name="username",
        ),
    ]
