# Generated by Django 4.1.4 on 2023-02-27 06:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_remove_useraddress_user_customuser_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_name",
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
