# Generated by Django 4.1.4 on 2023-03-13 09:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_rename_user_name_customuser_username"),
    ]

    operations = [
        migrations.RenameField(
            model_name="useraddress",
            old_name="user_id",
            new_name="user",
        ),
    ]
