# Generated by Django 4.1.4 on 2023-07-07 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_customuser_first_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserLogEntry",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("User was created", "Created"),
                            ("User was activated", "Activated"),
                            ("Users password was changed", "Password"),
                            ("User info was changed", "User Info"),
                            ("Users permissions were changed", "Permissions"),
                            ("Users email was changed", "Email"),
                        ],
                        default="Created",
                        max_length=255,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
