# Generated by Django 4.1.4 on 2023-04-06 07:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_rename_user_id_useraddress_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="useraddress",
            options={"verbose_name_plural": "User addresses"},
        ),
    ]
