# Generated by Django 4.1.4 on 2023-07-10 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_userlogentry"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userlogentry",
            name="user",
        ),
        migrations.AddField(
            model_name="userlogentry",
            name="target",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="target_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userlogentry",
            name="user_who_did_this_action",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
