# Generated by Django 4.1.4 on 2023-02-28 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_useraddress_linked_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraddress",
            name="linked_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="address_list",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
