# Generated by Django 4.1.4 on 2023-07-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_remove_userlogentry_user_userlogentry_target_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userlogentry",
            name="action",
            field=models.CharField(
                choices=[
                    ("User was created", "Created"),
                    ("User was activated", "Activated"),
                    ("Users password was changed", "Password"),
                    ("User info was changed", "User Info"),
                    ("User address info was changed", "User Address Info"),
                    ("User address info was deleted", "User Address Info Delete"),
                    ("Users permissions were changed", "Permissions"),
                    ("Users email was changed", "Email"),
                ],
                default="Created",
                max_length=255,
            ),
        ),
    ]
