# Generated by Django 4.1.4 on 2023-02-28 11:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_useraddress_linked_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="contact_person",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="joint_user",
        ),
    ]
