# Generated by Django 4.1.4 on 2023-07-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_alter_userlogentry_action"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersearchwatch",
            name="word",
        ),
        migrations.AddField(
            model_name="usersearchwatch",
            name="words",
            field=models.JSONField(default="tuoli"),
            preserve_default=False,
        ),
    ]
