# Generated by Django 4.1.4 on 2023-02-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_remove_customuser_contact_person_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.CharField(max_length=255),
        ),
    ]
