# Generated by Django 4.1.4 on 2023-07-24 08:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_remove_usersearchwatch_word_usersearchwatch_words"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserSearchWatch",
            new_name="SearchWatch",
        ),
    ]
