# Generated by Django 4.1.4 on 2023-11-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_rename_usersearchwatch_searchwatch"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="group",
            field=models.CharField(default="user_group", max_length=255),
            preserve_default=False,
        ),
    ]
