# Generated by Django 4.1.4 on 2023-11-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_customuser_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="group",
            field=models.CharField(
                choices=[
                    ("admin_group", "Admin"),
                    ("storage_group", "Storage"),
                    ("user_group", "User"),
                    ("bicycle_admin_group", "Bike Admin"),
                    ("bicycle_group", "Bike"),
                    ("deactive", "Deactive"),
                ],
                default="user_group",
                max_length=255,
            ),
        ),
    ]
