services:
    db:
        container_name: tavarat-kiertoon-db
        image: postgres:15.1-bullseye
        restart: unless-stopped
        env_file:
            - ".env"
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - tavaratnet

    nginx:
        build:
            context: .
            dockerfile: ./nginx/Dockerfile-prod
        env_file:
            - ".env"
        command: /bin/sh -c "export DOMAIN SSL_CERT SSL_KEY && envsubst '$$DOMAIN $$SSL_CERT $$SSL_KEY' < /etc/nginx/nginx.conf.tpl > /etc/nginx/conf.d/nginx.conf && nginx -g 'daemon off;'"
        ports:
          - "8000:8000"
        depends_on:
          - tavarat-kiertoon
        volumes:
          - medias:/medias
          - static:/static
          - /etc/ssl:/etc/ssl
        restart: "always"
        networks:
          - tavaratnet

    tavarat-kiertoon:
        container_name: tavarat-kiertoon-back
        build: .
        command: >
            sh -cx "python manage.py migrate && service cron start && python manage.py crontab add && gunicorn --config python:gunicorn_config tavarat_kiertoon.wsgi:application"
        # command: >
        #     sh -cx "python manage.py migrate && python manage.py seed && python manage.py runserver 0.0.0.0:8000"
        restart: unless-stopped
        ports:
            - "8989:8989"
        depends_on:
            - db
        volumes:
            - medias:/usr/src/app/media
            - static:/usr/src/app/static
            - /etc/ssl:/etc/ssl
        networks:
            - tavaratnet
        env_file:
            - ".env"

networks:
    tavaratnet:
        driver: bridge

volumes:
    postgres_data:
    medias:
    static: