# Generated by Django 4.1.4 on 2023-01-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactForm",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255)),
                ("subject", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(max_length=255)),
            ],
        ),
    ]
