# Generated by Django 4.1.4 on 2023-02-23 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ContactForm",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255)),
                ("subject", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("order_id", models.IntegerField(blank=True, null=True)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="Not read", max_length=255)),
            ],
        ),
    ]
