# Generated by Django 4.1.4 on 2023-01-19 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
