# Generated by Django 4.1.4 on 2023-02-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(max_length=100)),
            ],
        ),
    ]
