# Generated by Django 4.1.4 on 2023-11-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact_forms", "0002_alter_contactform_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactform",
            name="status",
            field=models.CharField(
                choices=[("Not read", "Not Read"), ("Read", "Read")],
                default="Not read",
                max_length=255,
            ),
        ),
    ]
