# Generated by Django 4.1.4 on 2023-02-10 11:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contact_forms", "0002_contacts"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Contacts",
            new_name="Contact",
        ),
        migrations.RenameField(
            model_name="contact",
            old_name="phoneNumber",
            new_name="phone_number",
        ),
    ]
