# Generated by Django 4.1.4 on 2023-02-20 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact_forms", "0003_rename_contacts_contact_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactform",
            name="category",
        ),
        migrations.AlterField(
            model_name="contactform",
            name="status",
            field=models.CharField(default="Not read", max_length=255),
        ),
    ]
