# Generated by Django 4.1.4 on 2023-02-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact_forms", "0004_remove_contactform_category_alter_contactform_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactform",
            name="order_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
