# Generated by Django 4.1.4 on 2023-01-18 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("storages", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Storages",
            new_name="Storage",
        ),
    ]
