# Generated by Django 4.1.4 on 2023-01-19 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hierarchy',
            name='categories_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_id', to='categories.category'),
        ),
        migrations.AlterField(
            model_name='hierarchy',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_id', to='categories.category'),
        ),
        migrations.AlterField(
            model_name='hierarchy',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_id', to='categories.category'),
        ),
    ]
