# Generated by Django 4.1.4 on 2023-01-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_hierarchy_categories_id_alter_hierarchy_child_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hierarchy',
            name='child',
        ),
        migrations.RemoveField(
            model_name='hierarchy',
            name='parent',
        ),
        migrations.AddField(
            model_name='hierarchy',
            name='child',
            field=models.ManyToManyField(blank=True, null=True, related_name='child_id', to='categories.category'),
        ),
        migrations.AddField(
            model_name='hierarchy',
            name='parent',
            field=models.ManyToManyField(blank=True, null=True, related_name='parent_id', to='categories.category'),
        ),
    ]
