# Generated by Django 4.1.4 on 2023-04-17 04:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bulletins", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bulletin",
            name="subject",
            field=models.ManyToManyField(blank=True, to="bulletins.bulletinsubject"),
        ),
    ]
