# Generated by Django 4.1.4 on 2023-04-17 04:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("status", models.CharField(max_length=255)),
                (
                    "delivery_address",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "contact",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                ("order_info", models.TextField(blank=True, default=None, null=True)),
                (
                    "delivery_date",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("phone_number", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ShoppingCart",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("date", models.DateTimeField(auto_now=True)),
                ("products", models.ManyToManyField(to="products.product")),
            ],
        ),
    ]
