# Generated by Django 4.1.4 on 2023-03-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="phone_number",
            field=models.CharField(default="1234567890", max_length=255),
            preserve_default=False,
        ),
    ]
