# Generated by Django 4.1.4 on 2023-01-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_order_contact_alter_order_delivery_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="contact",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_address",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_date",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_info",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
