# Generated by Django 4.1.4 on 2023-04-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_order_creation_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="contact",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_address",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_info",
            field=models.TextField(blank=True, default=""),
        ),
    ]
