# Generated by Django 4.1.4 on 2023-01-23 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_shoppingcart_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shoppingcart",
            name="order",
        ),
    ]
