# Generated by Django 4.1.4 on 2023-05-02 09:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_alter_order_contact_alter_order_delivery_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="contact",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_address",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
