# Generated by Django 4.1.4 on 2023-01-23 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_remove_shoppingcart_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shopping_cart",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="orders.shoppingcart",
            ),
        ),
    ]
