# Generated by Django 4.1.4 on 2023-05-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0009_remove_product_available_remove_product_barcode_and_more"),
        ("orders", "0005_alter_order_contact_alter_order_delivery_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="products",
            field=models.ManyToManyField(blank=True, to="products.productitem"),
        ),
        migrations.AlterField(
            model_name="shoppingcart",
            name="products",
            field=models.ManyToManyField(to="products.productitem"),
        ),
    ]
