# Generated by Django 4.1.4 on 2023-05-15 10:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0006_alter_order_products_alter_shoppingcart_products"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="products",
            new_name="productitems",
        ),
        migrations.RenameField(
            model_name="shoppingcart",
            old_name="products",
            new_name="productitems",
        ),
    ]
