# Generated by Django 4.1.4 on 2023-05-16 04:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0007_rename_products_order_productitems_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="productitems",
            new_name="product_items",
        ),
        migrations.RenameField(
            model_name="shoppingcart",
            old_name="productitems",
            new_name="product_items",
        ),
    ]
