# Generated by Django 4.1.4 on 2023-06-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0008_rename_productitems_order_product_items_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderEmailRecipient",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("email", models.CharField(max_length=255)),
            ],
        ),
    ]
