# Generated by Django 4.1.4 on 2023-06-16 05:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0008_rename_productitems_order_product_items_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Order is waiting for processing", "Waiting"),
                    ("Order is being processed", "Processing"),
                    ("Order has been delivered and finished", "Finished"),
                ],
                default="Order is waiting for processing",
                max_length=255,
            ),
        ),
    ]
