# Generated by Django 4.1.4 on 2023-06-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0009_orderemailrecipient"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_required",
            field=models.BooleanField(default=True),
        ),
    ]
