# Generated by Django 4.1.4 on 2023-06-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0009_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Waiting", "Waiting"),
                    ("Processing", "Processing"),
                    ("Finished", "Finished"),
                ],
                default="Order is waiting for processing",
                max_length=255,
            ),
        ),
    ]
