# Generated by Django 4.1.4 on 2023-06-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0010_order_delivery_required"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Waiting", "Waiting"),
                    ("Processing", "Processing"),
                    ("Finished", "Finished"),
                ],
                default="Waiting",
                max_length=255,
            ),
        ),
    ]
