# Generated by Django 4.1.4 on 2023-09-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0012_rename_contact_order_recipient_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="delivery_required",
            field=models.BooleanField(default=True),
        ),
    ]
