# Generated by Django 4.1.4 on 2023-03-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bikes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bikerental",
            name="extra_info",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
