# Generated by Django 4.1.4 on 2023-02-21 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
        ("bikes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bike",
            name="color",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.color",
            ),
        ),
    ]
