# Generated by Django 4.1.4 on 2023-02-27 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bikes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bikerental",
            name="bike_stock",
            field=models.ManyToManyField(related_name="rental", to="bikes.bikestock"),
        ),
        migrations.AlterField(
            model_name="bikestock",
            name="bike",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock",
                to="bikes.bike",
            ),
        ),
    ]
