# Generated by Django 4.1.4 on 2023-03-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bikes", "0002_alter_bikerental_extra_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="bikestock",
            name="package_only",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="bikestock",
            name="state",
            field=models.CharField(
                choices=[
                    ("AVAILABLE", "Available"),
                    ("MAINTENANCE", "Maintenance"),
                    ("RENTED", "Rented"),
                    ("RETIRED", "Retired"),
                ],
                default="AVAILABLE",
                max_length=255,
            ),
        ),
    ]
