# Generated by Django 4.1.4 on 2023-02-28 05:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bikes", "0002_alter_bikerental_bike_stock_alter_bikestock_bike"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bikestock",
            old_name="barcode",
            new_name="frame_number",
        ),
        migrations.AddField(
            model_name="bikestock",
            name="number",
            field=models.CharField(default=10, max_length=255),
            preserve_default=False,
        ),
    ]
