# Generated by Django 4.1.4 on 2023-04-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bikes", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bikerental",
            name="extra_info",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
