# Generated by Django 4.1.4 on 2023-05-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bikes", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BikePackages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                ("bikemodel", models.ManyToManyField(to="bikes.bikeamount")),
            ],
        ),
    ]
