# Generated by Django 4.1.4 on 2023-05-26 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0010_merge_20230526_0802"),
        ("bikes", "0003_alter_bikerental_extra_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="bike",
            name="picture",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.picture",
            ),
        ),
    ]
