# Generated by Django 4.1.4 on 2023-06-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bikes", "0004_bike_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bikestock",
            name="state",
            field=models.CharField(
                choices=[
                    ("AVAILABLE", "Available"),
                    ("MAINTENANCE", "Maintenance"),
                    ("RETIRED", "Retired"),
                ],
                default="AVAILABLE",
                max_length=255,
            ),
        ),
    ]
