# Generated by Django 4.1.4 on 2023-07-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bikes", "0006_bikestock_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bikerental",
            name="state",
            field=models.CharField(
                choices=[
                    ("WAITING", "Waiting"),
                    ("ACTIVE", "Active"),
                    ("FINISHED", "Finished"),
                ],
                default="WAITING",
                max_length=255,
            ),
        ),
    ]
