# Generated by Django 4.1.4 on 2023-08-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bikes", "0007_alter_bikerental_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="BikeTrailer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("register_number", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="BikeTrailerModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
            ],
        ),
    ]
