# Generated by Django 4.1.4 on 2023-07-21 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bikes", "0007_alter_bikerental_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="bikerental",
            name="packages",
            field=models.ManyToManyField(
                related_name="packages", to="bikes.bikepackage"
            ),
        ),
        migrations.AddField(
            model_name="bikestock",
            name="package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bike_stock",
                to="bikes.bikepackage",
            ),
        ),
    ]
