# Generated by Django 4.1.4 on 2023-11-06 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0020_alter_productitem_shelf_id"),
        ("bikes", "0008_remove_bike_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bikestock",
            name="storage",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.storage",
            ),
        ),
    ]
