# Generated by Django 4.1.4 on 2023-07-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bikes", "0008_bikerental_packages_bikestock_package"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bikerental",
            name="packages",
            field=models.ManyToManyField(
                related_name="packagerental", to="bikes.bikepackage"
            ),
        ),
    ]
