# Generated by Django 4.1.4 on 2023-08-15 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bikes", "0008_biketrailer_biketrailermodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="biketrailer",
            name="trailer_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="bikes.biketrailermodel",
            ),
        ),
    ]
