# Generated by Django 4.1.4 on 2023-11-13 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bikes", "0009_alter_bikestock_storage"),
    ]

    operations = [
        migrations.CreateModel(
            name="BikeTrailerModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name="bikestock",
            name="storage",
        ),
        migrations.CreateModel(
            name="BikeTrailer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("register_number", models.CharField(max_length=255)),
                (
                    "trailer_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trailer",
                        to="bikes.biketrailermodel",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="bikerental",
            name="bike_trailer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trailer_rental",
                to="bikes.biketrailer",
            ),
        ),
    ]
