# Generated by Django 4.1.4 on 2023-07-25 05:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bikes", "0009_alter_bikerental_packages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bikerental",
            name="bike_stock",
            field=models.ManyToManyField(
                blank=True, related_name="rental", to="bikes.bikestock"
            ),
        ),
        migrations.AlterField(
            model_name="bikerental",
            name="packages",
            field=models.ManyToManyField(
                blank=True, related_name="packagerental", to="bikes.bikepackage"
            ),
        ),
    ]
