# Generated by Django 4.1.4 on 2023-08-17 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bikes", "0009_biketrailer_trailer_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="bikerental",
            name="bike_trailer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trailer_rental",
                to="bikes.biketrailer",
            ),
        ),
        migrations.AlterField(
            model_name="biketrailer",
            name="trailer_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="trailer",
                to="bikes.biketrailermodel",
            ),
        ),
    ]
