# Generated by Django 4.1.4 on 2023-07-25 07:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bikes", "0010_alter_bikerental_bike_stock_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BikeAmount",
        ),
    ]
