# Generated by Django 4.1.4 on 2023-11-13 09:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bikes", "0010_biketrailermodel_remove_bikestock_storage_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bikerental",
            name="pickup",
        ),
    ]
