# Generated by Django 4.1.4 on 2023-12-01 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bikes", "0011_remove_bikerental_pickup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="biketrailer",
            name="trailer_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trailer",
                to="bikes.biketrailermodel",
            ),
        ),
    ]
