# Generated by Django 5.2.9 on 2026-09-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bikes", "0012_alter_biketrailer_trailer_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bikestock",
            name="state",
            field=models.CharField(
                choices=[
                    ("AVAILABLE", "Available"),
                    ("MAINTENANCE", "Maintenance"),
                    ("RENTED", "Rented"),
                    ("RETIRED", "Retired"),
                ],
                default="AVAILABLE",
                max_length=255,
            ),
        ),
    ]
