# Generated by Django 5.2.9 on 2026-09-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pauseshop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pause",
            name="department",
            field=models.CharField(
                choices=[("TAVARATKIERTOON", "Tavaratkiertoon"), ("BIKES", "Bikes")],
                default="TAVARATKIERTOON",
                max_length=255,
            ),
        ),
    ]
