# Generated by Django 4.1.4 on 2023-01-19 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storages', '0002_rename_storages_storage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('picture_address', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('available', models.BooleanField(default=False)),
                ('barcode', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('estimate_price', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(default=0.0)),
                ('shelf_id', models.IntegerField(blank=True, null=True)),
                ('free_description', models.TextField(blank=True, null=True)),
                ('condition', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('pictures', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.picture')),
                ('storages_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storages.storage')),
            ],
        ),
    ]
