# Generated by Django 4.1.4 on 2023-02-09 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Color",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Picture",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("picture_address", models.ImageField(upload_to="pictures")),
            ],
        ),
        migrations.CreateModel(
            name="Storage",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("in_use", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("available", models.BooleanField(default=False)),
                ("barcode", models.CharField(blank=True, max_length=255, null=True)),
                ("group_id", models.CharField(blank=True, max_length=255, null=True)),
                ("name", models.CharField(max_length=255)),
                ("price", models.FloatField(default=0.0)),
                ("shelf_id", models.IntegerField(blank=True, null=True)),
                ("free_description", models.TextField(blank=True, null=True)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "measurements",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("weight", models.FloatField(blank=True, default=0.0, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="categories.category",
                    ),
                ),
                (
                    "color",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.color",
                    ),
                ),
                ("pictures", models.ManyToManyField(to="products.picture")),
                (
                    "storages",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.storage",
                    ),
                ),
            ],
        ),
    ]
