# Generated by Django 4.1.4 on 2023-01-20 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='storages_id',
            new_name='storages',
        ),
    ]
