# Generated by Django 4.1.4 on 2023-01-19 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storages', '0002_rename_storages_storage'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='picture_address',
            field=models.ImageField(upload_to='pictures'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='pictures',
        ),
        migrations.AlterField(
            model_name='product',
            name='storages_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='storages.storage'),
        ),
        migrations.AddField(
            model_name='product',
            name='pictures',
            field=models.ManyToManyField(to='products.picture'),
        ),
    ]
