# Generated by Django 4.1.4 on 2023-04-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="modified_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
