# Generated by Django 4.1.4 on 2023-02-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="pictures",
            field=models.ManyToManyField(blank=True, to="products.picture"),
        ),
    ]
