# Generated by Django 4.1.4 on 2023-02-01 09:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_color_alter_product_color"),
    ]

    operations = [
        migrations.RenameField(
            model_name="color",
            old_name="color",
            new_name="name",
        ),
    ]
