# Generated by Django 4.1.4 on 2023-01-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_picture_picture_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='picture_address',
            field=models.ImageField(upload_to='media/pictures'),
        ),
    ]
