# Generated by Django 4.1.4 on 2023-04-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_product_modified_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="modified_date",
            field=models.DateTimeField(),
        ),
    ]
