# Generated by Django 4.1.4 on 2023-04-18 04:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_alter_product_modified_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="modified_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 18, 4, 48, 57, 135411, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
