# Generated by Django 4.1.4 on 2023-01-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_storage_alter_product_storages_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='group_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
