# Generated by Django 4.1.4 on 2023-01-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='in_use',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='group_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
