# Generated by Django 4.1.4 on 2023-04-20 04:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_alter_product_modified_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="modified_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
