# Generated by Django 4.1.4 on 2023-04-25 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0001_initial"),
        ("products", "0007_alter_product_modified_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="barcode",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="categories.category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="free_description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="product",
            name="group_id",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="product",
            name="measurements",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="product",
            name="storages",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.storage",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="weight",
            field=models.FloatField(default=0.0),
        ),
    ]
