# Generated by Django 4.1.4 on 2023-05-03 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0008_alter_product_barcode_alter_product_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModifyProduct",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "circumstance",
                    models.CharField(
                        choices=[
                            ("SHOPPING CART", "Shoppingcart"),
                            ("ORDER", "Order"),
                            ("STORAGE", "Storage"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="modified",
            field=models.ManyToManyField(blank=True, to="products.modifyproduct"),
        ),
    ]
