# Generated by Django 4.1.4 on 2023-05-15 06:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0008_alter_product_barcode_alter_product_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="available",
        ),
        migrations.RemoveField(
            model_name="product",
            name="barcode",
        ),
        migrations.RemoveField(
            model_name="product",
            name="date",
        ),
        migrations.RemoveField(
            model_name="product",
            name="group_id",
        ),
        migrations.RemoveField(
            model_name="product",
            name="modified_date",
        ),
        migrations.RemoveField(
            model_name="product",
            name="shelf_id",
        ),
        migrations.RemoveField(
            model_name="product",
            name="storages",
        ),
        migrations.CreateModel(
            name="ProductItem",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("available", models.BooleanField(default=False)),
                (
                    "modified_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("shelf_id", models.CharField(default="", max_length=255)),
                ("barcode", models.CharField(default="", max_length=255)),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.product",
                    ),
                ),
                (
                    "storage",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.storage",
                    ),
                ),
            ],
        ),
    ]
