# Generated by Django 4.1.4 on 2023-05-26 05:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0009_color_default"),
        ("products", "0009_remove_product_available_remove_product_barcode_and_more"),
    ]

    operations = []
