# Generated by Django 4.1.4 on 2023-05-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0009_modifyproduct_product_modified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modifyproduct",
            name="circumstance",
            field=models.CharField(
                choices=[
                    ("SHOPPING CART", "Shoppingcart"),
                    ("ORDER", "Order"),
                    ("STORAGE", "Storage"),
                    ("AVAILABLE", "Available"),
                    ("UNAVAILABLE", "Unavailable"),
                ],
                max_length=255,
            ),
        ),
    ]
