# Generated by Django 4.1.4 on 2023-05-29 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0010_merge_20230526_0802"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductItemLogEntry",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("Created", "Create"),
                            ("Added to shopping cart", "Cart Add"),
                            ("Removed from shopping cart", "Cart Remove"),
                            ("Timed out from shopping cart", "Cart Timeout"),
                            ("Ordered", "Order"),
                            ("Came back to circulation", "Circulation"),
                            ("Modified at storage", "Modify"),
                            ("Gifted away", "Gift"),
                        ],
                        default="Created",
                        max_length=255,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="productitem",
            name="log_entry",
            field=models.ManyToManyField(blank=True, to="products.productitemlogentry"),
        ),
    ]
