# Generated by Django 4.1.4 on 2023-05-29 07:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0011_productitemlogentry_productitem_log_entry"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productitem",
            old_name="log_entry",
            new_name="log_entries",
        ),
    ]
