# Generated by Django 4.1.4 on 2023-05-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0012_alter_modifyproduct_circumstance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modifyproduct",
            name="circumstance",
            field=models.CharField(
                choices=[
                    ("Added to shopping cart", "Addtocart"),
                    ("Removed from shopping cart", "Removefromcart"),
                    ("Timed out from shopping cart", "Timeoutfromcart"),
                    ("Ordered", "Order"),
                    ("Modified in storage", "Storage"),
                    ("Creation", "Creation"),
                    ("Returned to circulation", "Circulation"),
                ],
                max_length=255,
            ),
        ),
    ]
