# Generated by Django 4.1.4 on 2023-06-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0012_rename_log_entry_productitem_log_entries"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="color",
        ),
        migrations.AddField(
            model_name="product",
            name="color",
            field=models.ManyToManyField(blank=True, to="products.color"),
        ),
    ]
