# Generated by Django 4.1.4 on 2023-07-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0013_alter_productitemlogentry_action"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="color",
        ),
        migrations.AddField(
            model_name="product",
            name="color",
            field=models.ManyToManyField(blank=True, to="products.color"),
        ),
    ]
