# Generated by Django 4.1.4 on 2023-05-03 12:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0013_alter_modifyproduct_circumstance"),
    ]

    operations = [
        migrations.RenameField(
            model_name="modifyproduct",
            old_name="user",
            new_name="user1",
        ),
    ]
