# Generated by Django 4.1.4 on 2023-05-03 12:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0014_rename_user_modifyproduct_user1"),
    ]

    operations = [
        migrations.RenameField(
            model_name="modifyproduct",
            old_name="user1",
            new_name="loser",
        ),
    ]
