# Generated by Django 4.1.4 on 2023-05-03 12:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0015_rename_user1_modifyproduct_loser"),
    ]

    operations = [
        migrations.RenameField(
            model_name="modifyproduct",
            old_name="loser",
            new_name="user",
        ),
    ]
