# Generated by Django 4.1.4 on 2023-08-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0015_rename_color_product_colors"),
    ]

    operations = [
        migrations.AddField(
            model_name="storage",
            name="city",
            field=models.CharField(default="Turku", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="storage",
            name="zip_code",
            field=models.CharField(default="20100", max_length=255),
            preserve_default=False,
        ),
    ]
