# Generated by Django 4.1.4 on 2023-09-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0016_storage_city_storage_zip_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="productitem",
            name="item_status",
            field=models.CharField(
                choices=[
                    ("Available", "Available"),
                    ("In cart", "In Cart"),
                    ("Unavailable/in use", "Unavailable"),
                    ("Retired/gifted away", "Retired"),
                ],
                default="Available",
                max_length=255,
            ),
        ),
    ]
