# Generated by Django 4.1.4 on 2023-09-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0017_productitem_item_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productitem",
            name="item_status",
        ),
        migrations.AddField(
            model_name="productitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("Available", "Available"),
                    ("In cart", "In Cart"),
                    ("Unavailable", "Unavailable"),
                    ("Retired", "Retired"),
                ],
                default="Available",
                max_length=255,
            ),
        ),
    ]
