# Generated by Django 4.1.4 on 2023-09-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0018_remove_productitem_item_status_productitem_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productitem",
            name="available",
            field=models.BooleanField(default=True),
        ),
    ]
