# Generated by Django 4.1.4 on 2023-11-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0019_alter_productitem_available"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productitem",
            name="shelf_id",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
