# Generated by Django 4.1.4 on 2023-11-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0020_alter_productitem_shelf_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productitemlogentry",
            name="action",
            field=models.CharField(
                choices=[
                    ("Created", "Create"),
                    ("Added to shopping cart", "Cart Add"),
                    ("Removed from shopping cart", "Cart Remove"),
                    ("Timed out from shopping cart", "Cart Timeout"),
                    ("Ordered", "Order"),
                    ("Added to order", "Order Add"),
                    ("Removed from order", "Order Remove"),
                    ("Came back to circulation", "Circulation"),
                    ("Modified at storage", "Modify"),
                    ("Permanently removed from circulation", "Retired"),
                ],
                default="Created",
                max_length=255,
            ),
        ),
    ]
